apiVersion: v1
kind: Namespace
metadata:
  name: sample-golang
spec: {}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sample-golang
  name: p12file
  namespace: sample-golang
stringData:
  p12: "I'm not a real value"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-golang
  name: sample-golang
  namespace: sample-golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-golang
  template:
    metadata:
      labels:
        app: sample-golang
    spec:
      volumes:
      - name: p12file
        secret:
          secretName: p12file
      containers:
      - image: docker.io/esantoro/dp-sample-go:latest
        workingDir: "/app"
        name: dp-sample-go
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            port: 8080
            path: "/alive"
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 3
          httpGet:
            port: 8080
            path: "/ready"
        volumeMounts:
        - name: p12file
          subPath: p12
          mountPath: /app/file.p12

